FROM ubuntu

RUN apt update -y && \
    apt install -y default-jdk maven wget

RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz && \
    mkdir -p /opt/tomcat && \
    tar -xzf apache-tomcat-9.0.8.tar.gz -C /opt/tomcat && \
    rm apache-tomcat-9.0.8.tar.gz

RUN groupadd tomcat && \
    useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat

RUN chmod 755 /opt/tomcat/apache-tomcat-9.0.8/conf \
              /opt/tomcat/apache-tomcat-9.0.8/bin && \
    chown -R tomcat:tomcat /opt/tomcat/apache-tomcat-9.0.8

EXPOSE 8080

USER tomcat

CMD ["sh", "/opt/tomcat/apache-tomcat-9.0.8/bin/catalina.sh", "run"]
